server:
  port: 8080

spring:
  application:
    name: email-service
  datasource:
    url: jdbc:postgresql://localhost:5432/email_db
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: amqps://sykpwgcf:dOydO3o-zQ73O9esWeugbiDPIhV4JaYe@jackal.rmq.cloudamqp.com/sykpwgcf

broker:
  queue:
    email:
      name: default.email